import FreeCAD as App

doc = App.ActiveDocument

print("---- BOM List ----")

TypeId_Whitelist = [
    "App::Part",
    "App::Link",
    "Part::FeaturePython"
]


def traverse_object(object, level=0):
    # Classify object
    if object.TypeId == "App::Part" and object.Type == "Assembly":
        print("-"*level + f"Assembly: ({object.TypeId}) {object.Label}")

        # Go through child objects
        for ChildObjectName in object.getSubObjects():
            ChildObject = object.getSubObject(ChildObjectName, retType=1)
            traverse_object(ChildObject, level+1)

    elif object.TypeId == "App::Part":
        print("-"*level + f"Part: ({object.TypeId}) {object.Label}")

    elif object.TypeId == "App::Link":
        # Follow Link
        # print("-"*level + f"Link: ({object.TypeId}) {object.Label}")
        LinkedObject = object.LinkedObject
        traverse_object(LinkedObject, level)

    elif object.TypeId == "Part::FeaturePython" and object.ArrayType == "Circular Array":
        # print("-"*level + "Circular Array!")
        SourceObject = object.SourceObject

        for _ in range(object.Count):
            traverse_object(SourceObject, level)


for RootObject in doc.RootObjects:

    ## Find Root Assembly
	
    if RootObject.TypeId == "App::Part" and RootObject.Type == "Assembly":
        
        traverse_object(RootObject)